# Generated by Django 2.0.8 on 2020-06-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_added',
            new_name='date_ad',
        ),
    ]
